server:
  port: 10004
spring:
  application:
    name: member-service-nacos-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud_study?useSSL=false&useUnicode=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/ #配置Nacos地址
mybatis:
  mapper-locations: classpath:mapper/*.xml #指定mapper.xml 文件的位置
  type-aliases-package: cn.zyy.springcloud.entity #指定实体类所在的包 ,通过类名直接引用
#### eureka 客户端配置
#eureka:
#  client:
#    register-with-eureka: true #将自己注册到EurekaServer
#    fetch-registry: true #是否从从 EurekaServer 抓取注册信息，默认为 true, 单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡
#    service-url:
#      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka
management:   # TODO 不懂这里的配置是什么意思？
  endpoints:
    web:
      exposure:
        include: '*'
