spring:
  application:
    name: member-service-consumer-openfeign-80801
server:
  port: 8081

#euraka 客户端配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka, http://eureka9002.com:9002/eureka

