server:
  port: 10010
spring:
  application:
    name: seata-storage-micor-service
  cloud:
    alibaba:
      seata:
        tx-service-group: hspedu_order_tx_group #自定义事务组名称需要与 seata-server 中的对应,看 \conf\file.conf
    nacos:
      discovery:
        server-addr: localhost:8848  #配置Nacos Server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storage_micro_service?useSSL=false&useUnicode=true
    username: root
    password: root
mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    io:
      seata: info
debug: false